[workspace]
members =[
    "tmc-langs-cli",
    "tmc-langs-core",
    "tmc-langs-framework",
    "tmc-langs-util",

    "plugins/csharp",
    "plugins/java",
    "plugins/make",
    "plugins/notests",
    "plugins/python3",
    "plugins/r",
]
