[workspace]
members =[
    "tmc-langs-abstraction",
    "tmc-langs-cli",
    "tmc-langs-core",
    "tmc-langs-framework",
    "tmc-langs-java",
    "tmc-langs-make",
    "tmc-langs-notests",
    "tmc-langs-python3",
    "tmc-langs-util",
]
