[workspace]
members =[
    "tmc-langs-cli",
    "tmc-langs-core",
    "tmc-langs-csharp",
    "tmc-langs-framework",
    "tmc-langs-java",
    "tmc-langs-make",
    "tmc-langs-notests",
    "tmc-langs-python3",
    "tmc-langs-r",
    "tmc-langs-util",
]
