[package]
name = "tmc-langs-abstraction"
version = "0.1.0"
authors = ["Daniel Martinez <daniel.x.martinez@helsinki.fi>"]
edition = "2018"

[dependencies]
serde = { version = "1", features = ["derive"] }
