[package]
name = "tmc-langs-cli"
version = "0.1.0"
authors = ["Daniel Martinez <daniel.x.martinez@helsinki.fi>"]
edition = "2018"
description = "CLI client for TMC"

[dependencies]
tmc-langs-core = { path = "../tmc-langs-core" }
tmc-langs-framework = { path = "../tmc-langs-framework" }
tmc-langs-util = { path = "../tmc-langs-util" }
clap = "2"
walkdir = "2"
serde_json = "1"
env_logger = "0.7"
log = "0.4"
rpassword = "4"
url = "2"
serde = "1"
anyhow = "1"
quit = "1"
dirs = "3"
tempfile = "3"

[dev-dependencies]
tempfile = "3"
mockito = "0.26"
dotenv = "0.15"
