[package]
name = "tmc-langs-cli"
version = "0.1.0"
authors = ["Daniel Martinez <daniel.x.martinez@helsinki.fi>"]
edition = "2018"

[dependencies]
tmc-langs-util = { path = "../tmc-langs-util" }
tmc-langs-framework = { path = "../tmc-langs-framework" }
clap = "2"
isolang = "1"
walkdir = "2"
serde_json = "1.0"
env_logger = "0.7"
log = "0.4"

[dev-dependencies]
tempfile = "3"
