[package]
name = "tmc-langs-util"
version = "0.1.0"
authors = ["Daniel Martinez <daniel.x.martinez@helsinki.fi>"]
edition = "2018"

[dependencies]
tmc-langs-abstraction = { path = "../tmc-langs-abstraction" }
tmc-langs-framework = { path = "../tmc-langs-framework" }
isolang = "1"
