[package]
name = "tmc-langs-util"
version = "0.1.0"
authors = ["Daniel Martinez <daniel.x.martinez@helsinki.fi>"]
edition = "2018"

[dependencies]
tmc-langs-framework = { path = "../tmc-langs-framework" }
tmc-langs-csharp = { path = "../plugins/csharp" }
tmc-langs-java = { path = "../plugins/java" }
tmc-langs-make = { path = "../plugins/make" }
tmc-langs-notests = { path = "../plugins/notests" }
tmc-langs-python3 = { path = "../plugins/python3" }
tmc-langs-r = { path = "../plugins/r" }
log = "0.4"
tar = "0.4"
walkdir = "2"
tempfile = "3"
zip = "0.5"
shellwords = "1"
thiserror = "1"
impl-enum = "0.1"

[dev-dependencies]
env_logger = "0.7"
