[package]
name = "tmc-langs-util"
version = "0.1.0"
authors = ["Daniel Martinez <daniel.x.martinez@helsinki.fi>"]
edition = "2018"

[dependencies]
tmc-langs-abstraction = { path = "../tmc-langs-abstraction" }
tmc-langs-framework = { path = "../tmc-langs-framework" }
tmc-langs-python3 = { path = "../tmc-langs-python3" }
isolang = "1"
log = "0.4"
regex = "1"
lazy_static = "1"
tar = "0.4"
walkdir = "2"

[dev-dependencies]
env_logger = "0.7"
tempdir = "0.3"
