[package]
name = "tmc-langs-util"
version = "0.1.0"
authors = ["University of Helsinki <mooc@cs.helsinki.fi>", "Daniel Martinez <daniel.x.martinez@helsinki.fi>"]
edition = "2018"
license = "MIT OR Apache-2.0"

[dependencies]
tmc-langs-framework = { path = "../tmc-langs-framework" }
tmc-langs-csharp = { path = "../plugins/csharp" }
tmc-langs-java = { path = "../plugins/java" }
tmc-langs-make = { path = "../plugins/make" }
tmc-langs-notests = { path = "../plugins/notests" }
tmc-langs-python3 = { path = "../plugins/python3" }
tmc-langs-r = { path = "../plugins/r" }
log = "0.4"
tar = "0.4"
walkdir = "2"
tempfile = "3"
zip = "0.5"
shellwords = "1"
thiserror = "1"
impl-enum = "0.2"
zstd = "0.5"
lazy_static = "1"
regex = "1"
serde_yaml = "0.8"
md5 = "0.7"
serde = { version = "1", features = ["derive"] }
schemars = "0.8"

[target.'cfg(unix)'.dependencies]
nix = "0.19"

[dev-dependencies]
env_logger = "0.8"
