[package]
name = "tmc-langs-r"
version = "0.1.0"
authors = ["Daniel Martinez <daniel.x.martinez@helsinki.fi>"]
edition = "2018"

[dependencies]
tmc-langs-framework = { path = "../tmc-langs-framework" }
log = "0.4"
thiserror = "1"
serde_json = "1"

[dev-dependencies]
env_logger = "0.7"
