[package]
name = "tmc-langs-framework"
version = "0.1.0"
authors = ["University of Helsinki <mooc@cs.helsinki.fi>", "Daniel Martinez <daniel.x.martinez@helsinki.fi>"]
edition = "2018"
license = "MIT OR Apache-2.0"

[dependencies]
regex = "1"
lazy_static = "1"
log = "0.4"
walkdir = "2"
isolang = "1"
thiserror = "1"
serde = { version = "1", features = ["derive"] }
serde_yaml = "0.8"
zip = "0.5"
schemars = "0.8"
once_cell = "1"
nom = "6"
subprocess = "0.2"
tempfile = "3"
anyhow = "1"

[dev-dependencies]
env_logger = "0.8"
tempfile = "3"
mockall = "0.8"
simple_logger = "1"
