[package]
name = "tmc-langs-framework"
version = "0.1.0"
authors = ["Daniel Martinez <daniel.x.martinez@helsinki.fi>"]
edition = "2018"

[dependencies]
tmc-langs-abstraction = { path = "../tmc-langs-abstraction" }
regex = "1"
lazy_static = "1"
log = "0.4"
walkdir = "2"
isolang = "1"
thiserror = "1"

[dev-dependencies]
env_logger = "0.7"
tempdir = "0.3"
mockall = "0.7"
