name: Cargo fmt check

on:
  push:
    branches: [master, '[0-9]+.[0-9]+']
  pull_request:
    branches: [master, '[0-9]+.[0-9]+']

jobs:
  cargo_fmt_check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: cargo fmt -- --check
