name: Run tests

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

env:
  RUST_LOG: debug,j4rs=warn

jobs:
  linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install depedencies
        run: |
          sudo apt install -y check valgrind  # required for make plugin
          sudo apt install -y r-base  # required for R plugin
      - name: Install tmc-r-tester
        run: |
          Rscript -e 'install.packages(c("devtools","testthat", "httr", "curl"),repos="https://ftp.eenet.ee/pub/cran/")'
          Rscript -e 'devtools::install_github("RTMC/tmc-r-tester/tmcRtestrunner")'
      - name: Build test binary
        run: cargo test --no-run --verbose
      - name: Run tests
        run: cargo test --verbose --no-fail-fast

  windows:
    runs-on: windows-latest
    steps: # TODO: install valgrind and check?
      - uses: actions/checkout@v2
      - name: Build test binary
        run: cargo test --no-run --verbose
      - name: Run tests
        run: cargo test --verbose --no-fail-fast

  macos:
    runs-on: macos-latest
    steps: # TODO: install valgrind and check?
      - uses: actions/checkout@v2
      - name: Build test binary
        run: cargo test --no-run --verbose
      - name: Run tests
        run: cargo test --verbose --no-fail-fast
