name: Run tests

on:
  pull_request:
    branches: [master]

env:
  RUST_LOG: debug,j4rs=info

jobs:
  linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run tests
        run: |
          sudo apt install -y check valgrind  # required for make plugin
          cargo test --verbose

  windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run tests
        run: cargo test --verbose # TODO: install valgrind and check?

  macos:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run tests
        run: cargo test --verbose # TODO: install valgrind and check?
