name: Upload CLI binaries

on:
  release:
    types:
      - created

env:
  TAG: ${{ github.event.release.tag_name }} # had some issue using this directly on windows
  ACCEPT_EULA: Y # required for upgrade on ubuntu (msodbcsql17)

jobs:
  linux:
    runs-on: ubuntu-16.04
    strategy:
      matrix:
        target: [i686-unknown-linux-gnu, x86_64-unknown-linux-gnu]
    steps:
      - uses: actions/checkout@v2
      - uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}
      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -f # try to fix any broken packages
          sudo apt install -y gcc-5-multilib gcc-multilib # required to build for 32-bit arch
      - name: Cargo build
        run: |
          rustup target add i686-unknown-linux-gnu
          cargo build -p tmc-langs-cli --release --verbose --target ${{ matrix.target }}
      - name: Deploy
        run: gsutil cp target/${{ matrix.target }}/release/tmc-langs-cli gs://${{ secrets.GCP_BUCKET }}/tmc-langs-rust/tmc-langs-cli-${{ matrix.target }}-$TAG
