name: Upload CLI binaries

on:
  push

  windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
        with:
          project_id: tmc-langs
          service_account_key: ${{ secrets.GCP_SA_KEY }}
      - name: Build
        run: |
          python_version=$(python -c 'import sys; print(".".join(map(str, sys.version_info[:3])))')
          CLOUDSDK_PYTHON="C:\hostedtoolcache\windows\Python\\${python_version}\x64\python"
          echo $python_version
          echo $CLOUDSDK_PYTHON
          gsutil cp tmc-langs-cli-x86_64-pc-windows-msvc.exe gs://4c5fa153-643f-4d23-84c3-0b70e3bea571
