name: Upload CLI binaries

on:
  release:
    types:
      - created

env:
  TAG: ${{ github.event.release.tag_name }}

jobs:
  tag:
    runs-on: windows-latest
    steps:
      - name: try
        run: echo $Env:TAG
